export default [
    {
        id: '1',
        name: 'Charles',
        age: '5',
        ownerAge: '25',
        ownerName: 'Kat',
        image: 'https://i.pinimg.com/236x/5d/30/cc/5d30cce4a996e1465919a411d0ff7190--pure-joy-cakes.jpg',
    },
    {
        id: '2',
        name: 'Demi',
        age: '3',
        ownerAge: '35',
        ownerName: 'Alex',
        image: 'https://www.princeton.edu/sites/default/files/styles/half_2x/public/images/2022/02/KOA_Nassau_2697x1517.jpg?itok=iQEwihUn',
    },
    {
        id: '3',
        name: 'Ivy',
        age: '6',
        ownerAge: '27',
        ownerName: 'Bruno',
        image: 'https://arc-anglerfish-washpost-prod-washpost.s3.us-east-1.amazonaws.com/public/IJIIFKQ774I63AATSFCLQCU2D4_size-normalized.jpg',
    },
    {
        id: '4',
        name: 'Chonk',
        age: '7',
        ownerAge: '19',
        ownerName: 'Hannah',
        image: 'https://images.pexels.com/photos/58997/pexels-photo-58997.jpeg?cs=srgb&dl=pexels-muhannad-alatawi-58997.jpg&fm=jpg',
    },
    {
        id: '5',
        name: 'Luna',
        age: '1',
        ownerAge: '32',
        ownerName: 'Micheal',
        image: 'https://cdn-ajggd.nitrocdn.com/kMoOFpDlsOVtlYJLrnSRNCQXaUFHZPTY/assets/static/optimized/rev-9b0736f/wp-content/uploads/bb-plugin/cache/Pet-Photography-Alex-Cearns-1-1-landscape.jpg',
    },
    {
        id: '6',
        name: 'Fido',
        age: '7',
        ownerAge: '26',
        ownerName: 'Tyler',
        image: 'https://aercmn.com/wp-content/uploads/2020/08/1-1.png',
    },
    {
        id: '7',
        name: 'Demi',
        age: '3',
        ownerAge: '25',
        ownerName: 'Fran',
        image: 'https://petsolino.com/wp-content/uploads/2020/02/Should-You-DIY-Your-Dogs-Harness-1-1.jpg',
    },
    {
        id: '8',
        name: 'Flops',
        age: '10',
        ownerAge: '34',
        ownerName: 'Charlie',
        image: 'https://dogsnet.com/wp-content/uploads/2022/03/1-year-old-basset-hound-DN-long.jpg',
    },
    {
        id: '9',
        name: 'Bartholemule',
        age: '3000',
        ownerAge: '25000',
        ownerName: 'God Himself',
        image: 'https://people.com/thmb/m_fKur3LRPF4qlDwBAd0PBFNHSQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(999x0:1001x2)/bacon-the-dog-1-1-2000-665624bf445a4eeab2ee4b6f59dbd7e2.jpg',
    },
    {
        id: '10',
        name: 'Joe',
        age: '4',
        ownerAge: '36',
        ownerName: 'Bob',
        image: 'https://www.outsideonline.com/wp-content/uploads/2021/04/17/dog_head_square.jpg?crop=1:1&width=600&enable=upscale&quality=100',
    },
    {
        id: '1',
        name: 'Charles',
        age: '5',
        ownerAge: '25',
        ownerName: 'Kat',
        image: 'https://i.pinimg.com/236x/5d/30/cc/5d30cce4a996e1465919a411d0ff7190--pure-joy-cakes.jpg',
    },
    {
        id: '2',
        name: 'Demi',
        age: '3',
        ownerAge: '35',
        ownerName: 'Alex',
        image: 'https://www.princeton.edu/sites/default/files/styles/half_2x/public/images/2022/02/KOA_Nassau_2697x1517.jpg?itok=iQEwihUn',
    },
    {
        id: '3',
        name: 'Ivy',
        age: '6',
        ownerAge: '27',
        ownerName: 'Bruno',
        image: 'https://arc-anglerfish-washpost-prod-washpost.s3.us-east-1.amazonaws.com/public/IJIIFKQ774I63AATSFCLQCU2D4_size-normalized.jpg',
    },
    {
        id: '4',
        name: 'Chonk',
        age: '7',
        ownerAge: '19',
        ownerName: 'Hannah',
        image: 'https://images.pexels.com/photos/58997/pexels-photo-58997.jpeg?cs=srgb&dl=pexels-muhannad-alatawi-58997.jpg&fm=jpg',
    },
    {
        id: '5',
        name: 'Luna',
        age: '1',
        ownerAge: '32',
        ownerName: 'Micheal',
        image: 'https://cdn-ajggd.nitrocdn.com/kMoOFpDlsOVtlYJLrnSRNCQXaUFHZPTY/assets/static/optimized/rev-9b0736f/wp-content/uploads/bb-plugin/cache/Pet-Photography-Alex-Cearns-1-1-landscape.jpg',
    },
    {
        id: '6',
        name: 'Fido',
        age: '7',
        ownerAge: '26',
        ownerName: 'Tyler',
        image: 'https://aercmn.com/wp-content/uploads/2020/08/1-1.png',
    },
    {
        id: '7',
        name: 'Demi',
        age: '3',
        ownerAge: '25',
        ownerName: 'Fran',
        image: 'https://petsolino.com/wp-content/uploads/2020/02/Should-You-DIY-Your-Dogs-Harness-1-1.jpg',
    },
    {
        id: '8',
        name: 'Flops',
        age: '10',
        ownerAge: '34',
        ownerName: 'Charlie',
        image: 'https://dogsnet.com/wp-content/uploads/2022/03/1-year-old-basset-hound-DN-long.jpg',
    },
    {
        id: '9',
        name: 'Bartholemule',
        age: '3000',
        ownerAge: '25000',
        ownerName: 'God Himself',
        image: 'https://people.com/thmb/m_fKur3LRPF4qlDwBAd0PBFNHSQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(999x0:1001x2)/bacon-the-dog-1-1-2000-665624bf445a4eeab2ee4b6f59dbd7e2.jpg',
    },
    {
        id: '10',
        name: 'Joe',
        age: '4',
        ownerAge: '36',
        ownerName: 'Bob',
        image: 'https://www.outsideonline.com/wp-content/uploads/2021/04/17/dog_head_square.jpg?crop=1:1&width=600&enable=upscale&quality=100',
    },
    {
        id: '1',
        name: 'Charles',
        age: '5',
        ownerAge: '25',
        ownerName: 'Kat',
        image: 'https://i.pinimg.com/236x/5d/30/cc/5d30cce4a996e1465919a411d0ff7190--pure-joy-cakes.jpg',
    },
    {
        id: '2',
        name: 'Demi',
        age: '3',
        ownerAge: '35',
        ownerName: 'Alex',
        image: 'https://www.princeton.edu/sites/default/files/styles/half_2x/public/images/2022/02/KOA_Nassau_2697x1517.jpg?itok=iQEwihUn',
    },
    {
        id: '3',
        name: 'Ivy',
        age: '6',
        ownerAge: '27',
        ownerName: 'Bruno',
        image: 'https://arc-anglerfish-washpost-prod-washpost.s3.us-east-1.amazonaws.com/public/IJIIFKQ774I63AATSFCLQCU2D4_size-normalized.jpg',
    },
    {
        id: '4',
        name: 'Chonk',
        age: '7',
        ownerAge: '19',
        ownerName: 'Hannah',
        image: 'https://images.pexels.com/photos/58997/pexels-photo-58997.jpeg?cs=srgb&dl=pexels-muhannad-alatawi-58997.jpg&fm=jpg',
    },
    {
        id: '5',
        name: 'Luna',
        age: '1',
        ownerAge: '32',
        ownerName: 'Micheal',
        image: 'https://cdn-ajggd.nitrocdn.com/kMoOFpDlsOVtlYJLrnSRNCQXaUFHZPTY/assets/static/optimized/rev-9b0736f/wp-content/uploads/bb-plugin/cache/Pet-Photography-Alex-Cearns-1-1-landscape.jpg',
    },
    {
        id: '6',
        name: 'Fido',
        age: '7',
        ownerAge: '26',
        ownerName: 'Tyler',
        image: 'https://aercmn.com/wp-content/uploads/2020/08/1-1.png',
    },
    {
        id: '7',
        name: 'Demi',
        age: '3',
        ownerAge: '25',
        ownerName: 'Fran',
        image: 'https://petsolino.com/wp-content/uploads/2020/02/Should-You-DIY-Your-Dogs-Harness-1-1.jpg',
    },
    {
        id: '8',
        name: 'Flops',
        age: '10',
        ownerAge: '34',
        ownerName: 'Charlie',
        image: 'https://dogsnet.com/wp-content/uploads/2022/03/1-year-old-basset-hound-DN-long.jpg',
    },
    {
        id: '9',
        name: 'Bartholemule',
        age: '3000',
        ownerAge: '25000',
        ownerName: 'God Himself',
        image: 'https://people.com/thmb/m_fKur3LRPF4qlDwBAd0PBFNHSQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(999x0:1001x2)/bacon-the-dog-1-1-2000-665624bf445a4eeab2ee4b6f59dbd7e2.jpg',
    },
    {
        id: '10',
        name: 'Joe',
        age: '4',
        ownerAge: '36',
        ownerName: 'Bob',
        image: 'https://www.outsideonline.com/wp-content/uploads/2021/04/17/dog_head_square.jpg?crop=1:1&width=600&enable=upscale&quality=100',
    },
];